import type { ActivityLogItem, Case, Notification, SpecialistMember, UserProfile } from '@/context/AppContext';

export const defaultUserProfile: UserProfile = {
  id: 'user_default',
  title: 'Dr.',
  firstName: 'Admin',
  lastName: 'User',
  specialty: 'General Medicine',
  hospital: 'โรงพยาบาลพุทธชินราช พิษณุโลก',
  email: 'admin@example.com',
  avatarUrl: null,
  phoneNumber: '0800000000',
  isAcceptingCases: true,
  isAcceptingNotifications: true,
  license: 'MD-0001',
  telegramChatId: null,
  notifPrefs: {
    telegram: true,
    newRequest: true,
    requestApproved: true,
    newMessage: true,
    caseUpdate: true,
    systemAlert: true,
  },
};

export const defaultRequests: Case[] = [
  {
    id: 'REQ-1001',
    patientName: 'Somsak K.',
    hospital: 'โรงพยาบาลเมืองพิษณุโลก',
    status: 'Pending',
    priority: 'URGENT',
    date: 'Apr 2, 2026',
    specialty: 'Cardiology',
    age: 68,
    gender: 'Male',
    reason: 'Chest pain and shortness of breath',
    type: 'incoming',
    lastAction: 'Awaiting review',
    lastActiveTime: '12 min ago',
    senderId: 'user_01',
    hn: 'HN1001',
    an: 'AN1001',
    cid: '1111700200011',
    bloodType: 'A',
    allergies: ['Penicillin'],
    conditions: ['Hypertension'],
    currentSymptoms: 'Severe chest tightness for 2 hours, associated with diaphoresis.',
    initialDiagnosis: 'Suspected ACS',
    clinicalNotes: 'ECG recommended immediately.',
  },
  {
    id: 'REQ-1002',
    patientName: 'Malee P.',
    hospital: 'โรงพยาบาลบางกระทุ่ม',
    status: 'Pending',
    priority: 'SEMI-URGENT',
    date: 'Apr 2, 2026',
    specialty: 'Internal Medicine',
    age: 54,
    gender: 'Female',
    reason: 'Fever and cough',
    type: 'incoming',
    lastAction: 'Waiting for specialist',
    lastActiveTime: '28 min ago',
    senderId: 'user_02',
    hn: 'HN1002',
    an: 'AN1002',
    cid: '1111700200022',
    bloodType: 'B',
    allergies: [],
    conditions: ['Diabetes'],
    currentSymptoms: 'Fever 38.5 C with productive cough for 3 days.',
    initialDiagnosis: 'Possible pneumonia',
    clinicalNotes: 'Started empiric antibiotics.',
  },
];

export const defaultActiveCases: Case[] = [
  {
    id: 'CASE-2001',
    patientName: 'Niran S.',
    hospital: 'โรงพยาบาลพรหมพิราม',
    status: 'Active',
    priority: 'EMERGENCY',
    date: 'Apr 1, 2026',
    specialty: 'Neurology',
    age: 71,
    gender: 'Male',
    reason: 'Altered consciousness',
    type: 'incoming',
    lastAction: 'Neurology consult in progress',
    lastActiveTime: '5 min ago',
    senderId: 'user_03',
    hn: 'HN2001',
    an: 'AN2001',
    cid: '1111700200033',
    bloodType: 'O',
    allergies: ['Latex'],
    conditions: ['Stroke'],
    currentSymptoms: 'Acute drop in GCS to 10 with right-sided weakness noted this morning.',
    initialDiagnosis: 'Acute stroke',
    clinicalNotes: 'CT brain pending.',
  },
  {
    id: 'CASE-2002',
    patientName: 'Sudarat K.',
    hospital: 'โรงพยาบาลวังทอง',
    status: 'Critical',
    priority: 'IMMEDIATE',
    date: 'Apr 1, 2026',
    specialty: 'Pulmonology',
    age: 46,
    gender: 'Female',
    reason: 'Respiratory distress',
    type: 'sent',
    lastAction: 'ICU transfer arranged',
    lastActiveTime: '18 min ago',
    senderId: 'user_04',
    hn: 'HN2002',
    an: 'AN2002',
    cid: '1111700200044',
    bloodType: 'B',
    allergies: [],
    conditions: ['Asthma'],
    currentSymptoms: 'Progressive wheezing and dyspnea with SpO2 88% on room air.',
    initialDiagnosis: 'Acute asthma exacerbation',
    clinicalNotes: 'BiPAP started.',
  },
];

export const defaultArchiveCases: Case[] = [];

export const defaultNotifications: Notification[] = [
  { id: 'notif_1', title: 'New request received', message: 'A new consult request needs attention.', time: '10 min ago', read: false, type: 'request' },
  { id: 'notif_2', title: 'Case updated', message: 'Critical case status changed to Active.', time: '32 min ago', read: false, type: 'alert' },
];

export const defaultActivities: ActivityLogItem[] = [
  { id: 'act_1', title: 'Request received', desc: 'Cardiology request created', time: '12 min ago', icon: 'alert', timestamp: Date.now() - 12 * 60 * 1000 },
  { id: 'act_2', title: 'Case reviewed', desc: 'Neurology consult reviewed', time: '40 min ago', icon: 'note', timestamp: Date.now() - 40 * 60 * 1000 },
];

export const defaultSpecialists: SpecialistMember[] = [
  {
    id: 'sp_1',
    title: 'Dr.',
    firstName: 'Anong',
    lastName: 'Kittisak',
    specialty: 'Cardiology',
    hospital: 'โรงพยาบาลพุทธชินราช พิษณุโลก',
    email: 'anong@example.com',
    avatarUrl: null,
    phoneNumber: '0811111111',
    isAcceptingCases: true,
    isAcceptingNotifications: true,
    license: 'MD-1001',
    telegramChatId: null,
    notifPrefs: defaultUserProfile.notifPrefs,
    status: 'online',
  },
];
