export const SPECIALTY_OPTIONS = [
  'Anatomical Pathology',
  'Anesthesiology',
  'Cardiology',
  'Child and Adolescent Psychiatry',
  'Clinical Pathology',
  'Colon and Rectal Surgery',
  'Diagnostic Radiology',
  'Emergency Medicine',
  'Endocrinology and Metabolism',
  'Family Medicine',
  'Forensic Medicine',
  'Gastroenterology',
  'General Practitioner (GP)',
  'Geriatric Medicine',
  'Hematology',
  'Infectious Diseases',
  'Internal Medicine',
  'Medical Oncology',
  'Neonatal and Perinatal Medicine',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics and Gynecology',
  'Ophthalmology',
  'Orthopedic Surgery',
  'Otolaryngology',
  'Pathology',
  'Pediatric Cardiology',
  'Pediatric Endocrinology',
  'Pediatric Hematology and Oncology',
  'Pediatric Infectious Diseases',
  'Pediatric Nephrology',
  'Pediatric Neurology',
  'Pediatric Pulmonology',
  'Pediatric Surgery',
  'Pediatrics',
  'Plastic Surgery',
  'Preventive Medicine',
  'Psychiatry',
  'Pulmonary Medicine and Critical Care',
  'Radiation Oncology',
  'Radiology',
  'Registered Nurse',
  'Rehabilitation Medicine',
  'Rheumatology',
  'Surgery',
  'Thoracic Surgery',
  'Urology',
  'Vascular Surgery',
] as const;
