/**
 * The application now uses the restored HOS-style MariaDB schema:
 * provider, patient, case_register, case_vital, case_lab, and related tables.
 *
 * Seed data for this schema is maintained as SQL dumps, not as TypeScript
 * fixture rows, because table ids and foreign keys are generated by MariaDB.
 */
async function main() {
  console.log('Database seed is disabled for the restored MariaDB schema.');
  console.log('Restore a current icuconsult_*.sql dump instead.');
}

main().catch((error) => {
  console.error('Seed command failed:', error);
  process.exit(1);
});
